import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { DendriteIndex } from "./index.js";

const CATALOG_REL = "brain/_dendrite/catalog.md";

/** Regenerate a human- and agent-readable vault map inside the Obsidian vault. */
export function writeVaultCatalog(vaultPath: string, index: DendriteIndex): string {
  const notes = index.listAllNotes();
  const counts = index.compartmentCounts();
  const generated = new Date().toISOString();

  const lines: string[] = [
    "---",
    "title: Dendrite Vault Catalog",
    "dendrite: catalog",
    "generated: " + generated,
    "note_count: " + notes.length,
    "---",
    "",
    "# Vault catalog",
    "",
    "Auto-generated by Dendrite. Every filed note is indexed in SQLite at `~/.local/share/dendrite/index.db`.",
    "Agents: use MCP `search_vault`, `vault_catalog`, or read this file.",
    "",
    "## Summary",
    "",
  ];

  for (const [comp, count] of Object.entries(counts).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`- **${comp}**: ${count} note(s)`);
  }

  lines.push("", "## All notes", "");

  let lastComp = "";
  for (const note of notes) {
    if (note.compartment !== lastComp) {
      lastComp = note.compartment;
      lines.push(`### ${lastComp}`, "");
    }
    const slug = note.path.replace(/\.md$/, "").split("/").pop() ?? note.path;
    const ent = note.entities.length ? ` · _${note.entities.slice(0, 4).join(", ")}_` : "";
    lines.push(`- \`${note.path}\` — **${note.title}**${ent}`);
    if (note.summary) lines.push(`  - ${note.summary.slice(0, 160)}`);
  }

  lines.push("");

  const abs = join(vaultPath, CATALOG_REL);
  mkdirSync(join(vaultPath, "brain", "_dendrite"), { recursive: true });
  writeFileSync(abs, lines.join("\n"), "utf8");
  return CATALOG_REL;
}

export { CATALOG_REL };
